site_name: AgroMart - Grupo Ada Lovelace
site_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01--ADA-LOVELACE
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01--ADA-LOVELACE
repo_name: 2025-1-T01--ADA-LOVELACE

nav:
  - Fase 1: index.md
  - Fase 2: gqm/gqm-fase-definicao.md
  - Fase 3: plano/plano-de-medicao.md
  - Fase 4: avaliacao/avaliacao-projeto.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png

  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - toc.integrate

  palette:
    # ðŸŒž Tema Claro
    - scheme: default
      primary: blue grey
      accent: green
      toggle:
        icon: material/weather-night
        name: Alternar para o modo escuro

    # ðŸŒ™ Tema Escuro
    - scheme: slate
      primary: blue grey
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Alternar para o modo claro
